export const ON_GET_USER_IS_LOGGED_SUCCEEDED = "ON_GET_USER_IS_LOGGED_SUCCEEDED"
export const ON_GET_USER_IS_LOGGED_FAILED = "ON_GET_USER_IS_LOGGED_FAILED"

export const ON_GET_OPEN_CHECKOUT_CHAT_SUCCEEDED = "ON_GET_OPEN_CHECKOUT_CHAT_SUCCEEDED"

export const ON_ENTER_CP = "ON_ENTER_CP"

export const ON_CALCULATE_AB_RATING = "ON_CALCULATE_AB_RATING"

export const ON_GET_B2B_SEND_DATA_SUCCEEDED = "ON_GET_B2B_SEND_DATA_SUCCEEDED"
export const ON_GET_B2B_SEND_DATA_FAILED = "ON_GET_B2B_SEND_DATA_FAILED"

export const ON_GET_HIDE_NAVBAR_BY_ATC = "ON_GET_HIDE_NAVBAR_BY_ATC"
export const ON_GET_SHOW_NAVBAR_BY_ATC = "ON_GET_SHOW_NAVBAR_BY_ATC"

export const ON_GET_ABANDONED_POPUP_CLICKED = "ON_GET_ABANDONED_POPUP_CLICKED"

export const ON_GET_CHAT_NAVIGATION = "ON_GET_CHAT_NAVIGATION"

export const ON_GET_CHAT_LOADED_SUCCEEDED = "ON_GET_CHAT_LOADED_SUCCEEDED"
export const ON_GET_CHAT_LOADED_FAILED = "ON_GET_CHAT_LOADED_FAILED"

export const ON_SEND_KLAVIYO_CLIENT_EVENT = "ON_SEND_KLAVIYO_CLIENT_EVENT"

export const ON_SEND_DATA_TO_NOTION_SUCCEEDED = "ON_SEND_DATA_TO_NOTION_SUCCEEDED"
export const ON_SEND_DATA_TO_NOTION_FAILED = "ON_SEND_DATA_TO_NOTION_FAILED"
